#!/bin/sh
# Fuctions

# lorem() {
#   grep -m $1 "\S*\s" ~/.config/dotfiles/lorem | sed ':a;N;$!ba;s/\n//g'
# }

home(){
  if tmux ls -F '#S' | grep -q home ; then
    tmux attach -t 'home'
  else
    tmux new-session -d
    tmux rename-session 'home'
    tmux attach-session
  fi
}

attachedToTmux() {
  [ -z ${TMUX} ]
}


ef() {
  tempfzfpath=`fd . --hidden --ignore-file ~/.config/dotfiles/fdignore --type f | fzf --layout=reverse --height=50%`
  if [ -z ${tempfzfpath} ]; then
    echo exit no selection
  else
    echo $tempfzfpath
    if attachedToTmux ; then
      nvim $tempfzfpath
    else
      tmux new-window nvim $tempfzfpath
    fi
  fi
}

fe() {
  tempfzfpath=`fd . --hidden --ignore-file ~/.config/dotfiles/fdignore --type f | fzf --layout=reverse --height=50%`
  if [ -z $1 ] ; then
    echo $tempfzfpath
  else
    $1 $tempfzfpath
  fi
}

fmf() {
  tempfzfpath=`fd . --hidden --ignore-file ~/.config/dotfiles/fdignore --type f | fzf --layout=reverse --height=50%`
  if [ -z ${tempfzfpath} ]; then
    echo exit no selection
  else
    echo $tempfzfpath
    if attachedToTmux ; then
      vifmrun --select $tempfzfpath
    else
      tmux new-window vifmrun --select $tempfzfpath
    fi
  fi
}

cdf() {
  tempfzfpath=`fd . --hidden --ignore-file ~/.config/dotfiles/fdignore --type d | fzf --layout=reverse --height=50%`
  if [ -z ${tempfzfpath} ]; then
    echo exit no selection
  else
    echo $tempfzfpath
    cd $tempfzfpath
  fi
}

tmf() {
  tempfzfpath=`fd . --hidden --ignore-file ~/.config/dotfiles/fdignore --type d | fzf --layout=reverse --height=50%`
  if [ -z ${tempfzfpath} ]; then
    echo exit no selection
  else
    echo $tempfzfpath
    if attachedToTmux ; then
      tmux new-session -c $tempfzfpath
    else
      tmux new-window -c $tempfzfpath
    fi
  fi
}
