#!/bin/sh

if git status -s 1>/dev/null 2>/dev/null
then
  ls $@ --color=never |
    while read line
    do
      gstatus=`git status -s $line 2>/dev/null | head -1 | grep "^.." -o`
      if [ -n "$gstatus" ]
      then
        echo -n "$gstatus" | grep "^." -o | tr -d \\n | colorOnce 32
        echo -n "$gstatus" | grep ".$" -o | tr -d \\n | colorOnce 31
        echo -n ' '
      else
        echo -n "   "
      fi
      if echo $last | grep $line 
      then
        echo hi
        ls --color -d $line | tr -d \\n
     else
        ls --color -d $line
      fi
    done
  else
  ls $@
fi
