#!/bin/sh
insert="false"

xmodmap -e "keycode 65 = underscore"

while [ "$insert" = "false" ];
do
  runName=`ls $HOME/Scripts/run | dmenu -n`
  echo $ch
  if [ "$runName" = "i" ]; then
    insert="true"
  else
    $HOME/Scripts/run/$runName
  fi
done

xmodmap -e "keycode 65 = space"
exit
